---
sudo: false
language: ruby
cache: bundler
script: "bin/travis_check.sh"
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.1
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0" STDLIB_LOG_DEPRECATIONS="false"
  - rvm: 2.1.9
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 4.0" STDLIB_LOG_DEPRECATIONS="false"
  - rvm: 2.1.5
    bundler_args: --without system_tests
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
notifications:
  email:
    - al@example42.com
