---
language: ruby
install:
  - wget 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest' -q -O pdk.deb && sudo dpkg -i pdk.deb && rm pdk.deb
  - gem install r10k
  - r10k puppetfile install -v
stages:
  - validate
  - unit
jobs:
  include:
    - stage: validate
      script:
        - pdk validate metadata 2> /dev/null
        - pdk validate puppet site/ manifests/ 2> /dev/null

    - stage: unit
      script: pdk test unit 2> /dev/null
notifications:
  email: false
