---
# Noop mode. Uncomment to enable nood mode globally
noop_mode: true

# General psick settings
psick::manage: true
psick::auto_conf: 'hardened'
psick::auto_prereq: true

# Tiny Puppet settings in psick module
# By default tp integrations are not enabled. We want some of them:
psick::tp:
  cli_enable: true
  test_enable: true

# First run optional settings
psick::firstrun:
  enable: false
  fact_name: firstrun
  fact_value: done
psick::firstrun::linux_classes:
  hostname: '::psick::hostname'
#  packages: '::psick::aws::sdk'
psick::firstrun::windows_classes:
  hostname: '::psick::hostname'
#  packages: '::psick::aws::sdk'

# Common Linux classes
psick::pre::linux_classes:
  puppet: '::puppet'
  hostname: '::psick::hostname'
  hosts: '::psick::hosts::resource'
  dns: '::psick::dns::resolver'
  repo: '::psick::repo'
psick::base::linux_classes:
  mail: '::psick::postfix::tp'
  ssh: '::psick::openssh::tp'
  users: '::psick::users::static'
  sudo: '::psick::sudo'
  logs: '::psick::logs::rsyslog'
  time: '::psick::time'
  sysctl: '::psick::sysctl'
  update: '::psick::update'
  motd: '::psick::motd'
  profile: '::psick::profile'
  network: '::network'

# Pre and Base psick settings Windows
psick::pre::windows_classes:
  hosts: '::psick::hosts::resource'
psick::base::windows_classes:
  features: '::psick::windows::features'
  registry: '::psick::windows::registry'
  services: '::psick::windows::services'
  time: '::psick::time'
#   users: '::psick::users::ad'

# Repo settings
psick::repo::add_defaults: true

# Time settings
psick::time::servers:
  - 'pool.ntp.org'

# Timezone settings
psick::timezone::timezone: 'UTC'

# Hostname and network settings
psick::hostname::update_network_entry: false # Avoid resource duplication when psick::network is used

# Sample monitor settings
psick::linux::monitor_classes:
#    nrpe: '::psick::monitor::nrpe'
#    icinga: '::psick::icinga2'
#    nagiosplugins: '::psick::monitor::nagiosplugins'
    systat: '::psick::monitor::sar'

# Postfix configuration
psick::postfix::tp:
  auto_conf: true
  tp_hash:
    tp::conf:
      postfix:
        template: 'psick/postfix/main.cf.erb'
      postfix::sample:
        content: sample
    tp::dir:
      postfix::dir:
        owner: postfix

# Sample user settings
#  psick::users::static::root_pw: hash_as_in_etc_shadow
#  psick::users::static::delete_unmanaged: false
#  psick::users::static::managed_users_hash:
#    al:
#      sshkey_content:
#        key: AAAAB3NzaC1yc2E....
#        type: ssh-rsa
#        comment: al@macante.local

# Sample sudo settings
#psick::sudo::admins:
#  - al
#psick::sudo::sudoers_template: 'psick/sudo/sudoers.erb'

# Sample sysctl settings
psick::sysctl::settings_hash:
  net.ipv4.conf.all.forwarding: 0

# AWS region
psick::aws::region: eu-central-1

