---
# Noop mode. Uncomment to enable nood mode globally
noop_mode: true

# Tiny Puppet settings in psick module
# By default tp integrations are not enabled. We want some of them:
psick::tp:
  cli_enable: true
  test_enable: true
  puppi_enable: false
  debug: false
  data_module: tinydata
  config_file_notify: true
  config_file_require: true
  config_dir_notify: true
  config_dir_require: true

# First run optional settings
psick::firstrun:
  enable: false
  fact_name: firstrun
  fact_value: done
psick::firstrun::linux::classes:
  hostname: '::psick::hostname'
#  packages: '::psick::aws::sdk'
psick::firstrun::windows::classes:
  hostname: '::psick::hostname'
#  packages: '::psick::aws::sdk'


psick::linux::base_classes:
  mail: '::psick::mail::postfix'
  puppet: '::puppet'
  ssh: '::psick::ssh::openssh'
  users: '::psick::users::static'
  sudo: '::psick::sudo'
  monitor: '::psick::monitor'
  logs: '::psick::logs::rsyslog'
  time: '::psick::time'
  sysctl: '::psick::sysctl'
  dns: '::psick::dns::resolver'
  hostname: '::psick::hostname'
  hosts: '::psick::hosts::resource'
  update: '::psick::update'
  motd: '::psick::motd'
  profile: '::psick::profile'
#  network: '::psick::network'

# Pre and Base psick settings Windows
psick::windows::base_classes:
  features: '::psick::windows::features'
  registry: '::psick::windows::registry'
#   users: '::psick::users::ad'
  hosts: '::psick::hosts::resource'
  time: '::psick::time'

# Repo settings
psick::repo::add_defaults: true

# Time settings
psick::time::servers:
  - 'pool.ntp.org'

# Timezone settings
psick::timezone::timezone: 'UTC'

# Sample monitor settings
psick::linux::monitor_classes:
#    nrpe: '::psick::monitor::nrpe'
#    icinga: '::psick::icinga2'
#    nagiosplugins: '::psick::monitor::nagiosplugins'
    systat: '::psick::monitor::sar'

# Sample user settings
#  psick::users::static::root_pw: hash_as_in_etc_shadow
#  psick::users::static::delete_unmanaged: false
#  psick::users::static::managed_users_hash:
#    al:
#      sshkey_content:
#        key: AAAAB3NzaC1yc2E....
#        type: ssh-rsa
#        comment: al@macante.local

# Sample sudo settings
# psick::sudo::admins:
#   - al
# psick::sudo::sudoers_template: 'psick/sudo/sudoers.erb'

# Sample sysctl settings
psick::sysctl::settings:
  net.ipv4.conf.all.forwarding: 0

# AWS region
psick::aws::region: eu-central-1

