---
# Default settings for vms
vm:
  memory: 1024
  cpu: 1
  box: centos7 # From boxes list below
  puppet_apply: true
  puppet_agent: false

network:
  range: 10.42.41.0/24
  ip_start_offset: 101
  domain: ci

puppet:
  version: latest
  env: test
  zone: ci
#  master_hostname: dev-local-puppet-01

# Nodes shown in vagrant status 
nodes:
  - role: git
    count: 1
    memory: 2048
  - role: ci
    count: 1
    memory: 2048
  - role: citest
    hostname_base: centos7
    count: 1
  - role: citest
    hostname_base: suse12
    box: suse12
    count: 1
  - role: citest
    hostname_base: ubuntu1604
    box: ubuntu1604
    count: 1
  - role: citest
    hostname_base: debian8
    box: debian8
    count: 1
  - role: citest
    hostname_base: alpine3
    box: alpine3
    count: 1

boxes:
  centos7:
    box: puppetlabs/centos-7.2-64-puppet
    breed: puppetlabs-centos7
  centos7_pe:
    box: puppetlabs/centos-7.0-64-puppet-enterprise
    breed: puppetlabs
  centos6:
    box: puppetlabs/centos-6.6-64-puppet
    breed: puppetlabs
  ubuntu1604:
    box: puppetlabs/ubuntu-16.04-64-puppet
    breed: puppetlabs-apt
  ubuntu1404:
    box: puppetlabs/ubuntu-14.04-64-puppet
    breed: puppetlabs-apt
  debian8:
    box: puppetlabs/debian-8.2-64-puppet
    breed: puppetlabs-apt
  alpine3:
    box: maier/alpine-3.3.1-x86_64
    breed: puppetlabs
# Image available for suse12 has issues. To setup correctly:
# vagrant up suse12
# vagrant provision suse12
# vagrant reload suse12
# vagrant provision suse12
  suse12:
    box: suse/sles12sp1
    breed: puppetlabs
