---
psick::linux::profiles:
  - '::docker'
  - '::docker::psick::builder'
##  - '::docker::psick::run_examples'
#  - '::docker::psick::build_examples'
  - '::psick::python::fabric'

psick::sysctl::settings:
  net.ipv4.conf.all.forwarding: 1

docker::username: example42
#docker::install_class: '' # To allow operations from Mac. Docker has to be installed.
docker::psick::run_examples::ensure: absent
docker::psick::builder::maintainer: 'Example42 GmbH <info@example42.com>'
docker::psick::builder::images:
  puppet-agent:
    ensure: present

