HOSTS:
  centos-7-x64:
    platform: el-7-x86_64
    hypervisor : docker
    image: centos:centos7
    docker_preserve_image: false
    mount_folders:
      controlrepo:
        host_path: .
        container_path: /etc/puppetlabs/code/environments/production
    docker_cmd: '["/usr/sbin/init"]'
    docker_image_commands:
      - 'yum -y swap -- remove fakesystemd -- install systemd systemd-libs'
      - 'yum -y install cronie initscripts which'
      - 'yum -y update; yum clean all'
      - 'rm -fr /var/cache/yum/x86_64/7/* /etc/yum.repos.d/*.repo'
CONFIG:
  type: foss
